const inlineStyles = {
  Box_D80C: {
    color: 'rgba(0, 0, 0, 0)',
    'maxWidth': '1200px',
    'backgroundColor': 'white',
    width: '100vw',
    padding: '2rem',
    display: 'flex',
    'flexDirection': 'column',
    'rowGap': '3rem',
    '@media(maxWidth:479px)': { 'rowGap': '1.8rem', padding: '0.8rem' },
  },
  Box_2EBB: { width: '100%' },
  Typography_2FCE: {
    display: 'flex',
    'fontSize': '24px',
    'fontFamily': 'sans-serif',
    color: 'black',
    width: 'fit-content',
  },
  Typography_48E8: {
    color: 'rgb(137, 144, 154)',
    'fontFamily': 'sans-serif',
    'fontSize': '16.5px',
    width: '100%',
    '@media(maxWidth:479px)': { 'fontSize': '13.5px' },
  },
  Box_5491: {
    display: 'flex',
    'flexDirection': 'column',
    'rowGap': '1rem',
    width:"40%",
    "@media (maxWidth:760px)": { minWidth:"450px"},
    '@media (maxWidth:479px)': {width:"100%" },
  },
  Box_CF5D: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    rowGap: '10px',
  },
  Label_EC0E: {
    display: 'flex',
    color: 'black',
    fontWeight: '700',
    fontSize: '17px',
    fontFamily: 'sans-serif',
    width: 'fit-content',
    '@media(maxWidth:479px)': { 'fontSize': '14.5px' },
  },
  Input_25DB: {
    'backgroundColor': 'transparent',
    border: '1px solid rgb(236, 238, 241)',
    color: 'rgb(137, 144, 154)',
    'fontFamily': 'sans-serif',
    'fontSize': '15px',
    padding: '15px',
    width: '100%',
    '@media(maxWidth:479px)': { 'fontSize': '13px', padding: '10px' },
  },
  Box_7363: {
    width: '100%',
    display: 'flex',
    'flexDirection': 'column',
    'rowGap': '10px',
  },
  Label_0FCC: {
    display: 'flex',
    color: 'black',
    'fontWeight': '700',
    'fontSize': '17px',
    'fontFamily': 'sans-serif',
    width: 'fit-content',
    '@media(maxWidth:479px)': { 'fontSize': '14.5px' },
  },
  Input_CE4C: {
    'backgroundColor': 'transparent',
    border: '1px solid rgb(236, 238, 241)',
    color: 'rgb(137, 144, 154)',
    'fontFamily': 'sans-serif',
    'fontSize': '15px',
    padding: '15px',
    width: '100%',
    '@media(maxWidth:479px)': { 'fontSize': '13px', padding: '10px' },
  },
  Box_E9D7: {
    width: '100%',
    display: 'flex',
    'flexDirection': 'column',
    'rowGap': '10px',
  },
  Label_D563: {
    display: 'flex',
    color: 'black',
    'fontWeight': '700',
    'fontSize': '17px',
    'fontFamily': 'sans-serif',
    width: 'fit-content',
    '@media(maxWidth:479px)': { 'fontSize': '14.5px' },
  },
  Input_DC90: {
    'backgroundColor': 'transparent',
    border: '1px solid rgb(236, 238, 241)',
    color: 'rgb(137, 144, 154)',
    'fontFamily': 'sans-serif',
    'fontSize': '15px',
    padding: '15px',
    width: '100%',
    '@media(maxWidth:479px)': { 'fontSize': '13px', padding: '10px' },
  },
  Button_3BBD: {
    'backgroundColor': 'rgb(104, 208, 208)',
    color: 'rgb(255, 255, 255)',
    cursor: 'pointer',
    display: 'flex',
    border: 'none',
    'borderRadius': '4px',
    padding: '14px 55px',
    'justifyContent': 'center',
  },
  Typography_2FCD: {
    color: 'rgb(255, 255, 255)',
    display: 'block',
    'fontFamily': 'sans-serif',
    'fontWeight': '600',
    '@media(maxWidth:479px)': { 'fontSize': '13.5px' },
  },
};
export { inlineStyles };
